import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1749834092520 implements MigrationInterface {
    name = 'InitialSchema1749834092520'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "target_audiences" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, CONSTRAINT "PK_f3d38ceec53c6c09952ca2fdf83" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "discount_options" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "percentage" numeric(5,2), "description" character varying, CONSTRAINT "PK_7ea0bc24dadf997c6972854c3ba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "features" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, CONSTRAINT "PK_5c1e336df2f4a7051e5bf08a941" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('client', 'coach', 'admin')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "email" character varying NOT NULL, "phone" character varying NOT NULL, "password" character varying NOT NULL, "role" "public"."users_role_enum" NOT NULL DEFAULT 'client', "isActive" boolean NOT NULL DEFAULT true, "isEmailVerified" boolean NOT NULL DEFAULT false, "emailVerificationToken" character varying, "emailVerificationExpires" TIMESTAMP, "isPhoneVerified" boolean NOT NULL DEFAULT false, "phoneVerificationCode" character varying, "phoneVerificationExpires" TIMESTAMP, "refreshToken" character varying, "refreshTokenExpires" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_a000cca60bcf04454e727699490" UNIQUE ("phone"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('task_completed', 'missed_task', 'new_trainee_joined', 'message_received', 'payment_due', 'workout_reminder', 'meal_reminder', 'goal_achieved', 'subscription_expired', 'certificate_expiring', 'profile_incomplete', 'system_update', 'promotional')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_status_enum" AS ENUM('read', 'unread')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."notifications_type_enum" NOT NULL, "header" character varying(200) NOT NULL, "description" text NOT NULL, "status" "public"."notifications_status_enum" NOT NULL DEFAULT 'unread', "navigationLink" character varying, "userId" uuid NOT NULL, "metadata" jsonb NOT NULL DEFAULT '{}', "timestamp" TIMESTAMP NOT NULL DEFAULT now(), "readAt" TIMESTAMP, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_aef1c7aef3725068e5540f8f00" ON "notifications" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_92f5d3a7779be163cbea7916c6" ON "notifications" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_692a909ee0fa9383e7859f9b40" ON "notifications" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5f0cceaef187f5c7884891c9e0" ON "notifications" ("timestamp") `);
        await queryRunner.query(`CREATE TYPE "public"."meals_mealtype_enum" AS ENUM('breakfast', 'lunch', 'dinner', 'snacks', 'drinks')`);
        await queryRunner.query(`CREATE TABLE "meals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "calories" numeric(8,2) NOT NULL, "protein" numeric(8,2) NOT NULL, "fat" numeric(8,2) NOT NULL, "carbs" numeric(8,2) NOT NULL, "ingredients" text array NOT NULL, "preparation" text NOT NULL, "imageUrl" character varying, "mealType" "public"."meals_mealtype_enum" NOT NULL, "description" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e6f830ac9b463433b58ad6f1a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."workouts_workouttype_enum" AS ENUM('strength', 'cardio', 'flexibility')`);
        await queryRunner.query(`CREATE TYPE "public"."workouts_difficulty_enum" AS ENUM('beginner', 'intermediate', 'advanced')`);
        await queryRunner.query(`CREATE TABLE "workouts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "description" text, "exercises" jsonb NOT NULL, "workoutType" "public"."workouts_workouttype_enum" NOT NULL, "duration" integer NOT NULL, "difficulty" "public"."workouts_difficulty_enum" NOT NULL, "media" jsonb NOT NULL DEFAULT '[]', "caloriesBurned" integer, "equipment" text array NOT NULL DEFAULT '{}', "targetMuscleGroups" text array NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5b2319bf64a674d40237dbb1697" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f610bb716b9281f07dd9c11d9f" ON "workouts" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_d84c274214f1881d1b9469841a" ON "workouts" ("workoutType") `);
        await queryRunner.query(`CREATE INDEX "IDX_7d1f61c30f0601093f80c5b053" ON "workouts" ("duration") `);
        await queryRunner.query(`CREATE INDEX "IDX_f371d2426c88d4cafeec9b4f0f" ON "workouts" ("difficulty") `);
        await queryRunner.query(`CREATE TYPE "public"."coach_profiles_gender_enum" AS ENUM('male', 'female', 'other', 'prefer_not_to_say')`);
        await queryRunner.query(`CREATE TYPE "public"."coach_profiles_fitnessareas_enum" AS ENUM('weight_loss', 'strength_training', 'cardio', 'yoga', 'pilates', 'hiit', 'crossfit', 'bodybuilding', 'flexibility', 'nutrition', 'sports_specific', 'rehabilitation', 'senior_fitness', 'prenatal_fitness', 'functional_training')`);
        await queryRunner.query(`CREATE TABLE "coach_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "bio" text, "specialization" character varying, "yearsOfExperience" integer, "certificates" jsonb DEFAULT '[]', "hourlyRate" numeric(10,2) NOT NULL DEFAULT '0', "profilePictureUrl" character varying, "gender" "public"."coach_profiles_gender_enum", "age" integer, "location" character varying, "fitnessAreas" "public"."coach_profiles_fitnessareas_enum" array DEFAULT '{}', "isVerified" boolean NOT NULL DEFAULT false, "rating" integer NOT NULL DEFAULT '0', "totalRatings" integer NOT NULL DEFAULT '0', "availableDays" text NOT NULL DEFAULT '', "availableHours" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "onboardingCompleted" boolean NOT NULL DEFAULT false, CONSTRAINT "REL_e6994e1be0dd7a878d437bbbcc" UNIQUE ("userId"), CONSTRAINT "PK_0f4001455b40350665f589642dc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."trainee_progress_subscriptionstatus_enum" AS ENUM('active', 'pending', 'suspended', 'cancelled')`);
        await queryRunner.query(`CREATE TYPE "public"."trainee_progress_lastactivitytype_enum" AS ENUM('workout_completed', 'meal_logged', 'weight_recorded', 'goal_achieved', 'check_in')`);
        await queryRunner.query(`CREATE TABLE "trainee_progress" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "traineeId" uuid NOT NULL, "coachId" uuid NOT NULL, "workoutCompletionPercentage" numeric(5,2) NOT NULL DEFAULT '0', "totalWorkoutsCompleted" integer NOT NULL DEFAULT '0', "currentWeight" numeric(5,2), "targetWeight" numeric(5,2), "subscriptionStatus" "public"."trainee_progress_subscriptionstatus_enum" NOT NULL DEFAULT 'pending', "subscriptionStartDate" date, "subscriptionEndDate" date, "lastActivityDate" TIMESTAMP, "lastActivityType" "public"."trainee_progress_lastactivitytype_enum", "notes" text, "progressData" jsonb NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f06b03e5ee65802df8b60e18d89" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_34f98167c1630fe2d745824cce" ON "trainee_progress" ("traineeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_02ded207ca1dd40e85d29feefd" ON "trainee_progress" ("coachId") `);
        await queryRunner.query(`CREATE INDEX "IDX_df1eb656efc9f5fda4f34565b3" ON "trainee_progress" ("subscriptionStatus") `);
        await queryRunner.query(`CREATE INDEX "IDX_481bbe1139541276b3dd613e22" ON "trainee_progress" ("lastActivityDate") `);
        await queryRunner.query(`CREATE TABLE "quotes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "text" text NOT NULL, "author" character varying(200) NOT NULL, "category" character varying(100) NOT NULL DEFAULT 'motivation', "isActive" boolean NOT NULL DEFAULT true, "timesServed" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_99a0e8bcbcd8719d3a41f23c263" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8375e4aeb4b966f81293171fad" ON "quotes" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_3bfcdfdee741415b1f37b3b6bf" ON "quotes" ("isActive") `);
        await queryRunner.query(`CREATE TYPE "public"."messages_type_enum" AS ENUM('text', 'image', 'file', 'system')`);
        await queryRunner.query(`CREATE TYPE "public"."messages_status_enum" AS ENUM('sent', 'delivered', 'read')`);
        await queryRunner.query(`CREATE TABLE "messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "senderId" uuid NOT NULL, "receiverId" uuid NOT NULL, "content" text NOT NULL, "type" "public"."messages_type_enum" NOT NULL DEFAULT 'text', "status" "public"."messages_status_enum" NOT NULL DEFAULT 'sent', "fileUrl" character varying, "fileType" character varying, "readAt" TIMESTAMP, "isArchived" boolean NOT NULL DEFAULT false, "threadId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2db9cf2b3ca111742793f6c37c" ON "messages" ("senderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_acf951a58e3b9611dd96ce8904" ON "messages" ("receiverId") `);
        await queryRunner.query(`CREATE INDEX "IDX_befd307485dbf0559d17e4a4d2" ON "messages" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_57eec5dc5b3e70ace7769466f8" ON "messages" ("isArchived") `);
        await queryRunner.query(`CREATE INDEX "IDX_15f9bd2bf472ff12b6ee20012d" ON "messages" ("threadId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6ce6acdb0801254590f8a78c08" ON "messages" ("createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."packages_skilllevel_enum" AS ENUM('Rookie', 'Warrior', 'Legend')`);
        await queryRunner.query(`CREATE TABLE "packages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" text NOT NULL, "country" character varying NOT NULL, "price" numeric(10,2) NOT NULL, "fitnessAreas" text array NOT NULL, "duration" integer NOT NULL, "features" text array, "sessionsNumber" integer, "sessionPeriod" integer, "skillLevel" "public"."packages_skilllevel_enum", "targetAudienceId" character varying, "imageUrl" character varying, "limitedAvailability" boolean NOT NULL DEFAULT false, "discountOptionId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "coachId" uuid, CONSTRAINT "PK_020801f620e21f943ead9311c98" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "client_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "bio" character varying, "age" integer, "weight" integer, "height" integer, "fitnessGoals" character varying, "healthConditions" character varying, "preferredWorkoutType" character varying, "profilePictureUrl" character varying, "gender" character varying, "location" character varying, "fitnessGoal" character varying, "fitnessLevel" character varying, "bodyShape" character varying, "mealsPerDay" integer, "specificDiet" boolean, "exerciseFrequency" integer, "sessionDuration" integer, "gymAccess" boolean, "healthConsiderations" character varying, "allergies" character varying, "medications" boolean, "medicalConditions" boolean, "medicalConditionsDescription" character varying, "smoke" boolean, "drinkAlcohol" boolean, "coachGenderPreference" character varying, "coachingMode" character varying, "budget" character varying, "preferredTime" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_af81cdb71317b2f0f6cb6bce77" UNIQUE ("userId"), CONSTRAINT "PK_fc4acd4b04f4a0537e7213f8ddd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coach_profiles" ADD CONSTRAINT "FK_e6994e1be0dd7a878d437bbbcc0" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trainee_progress" ADD CONSTRAINT "FK_34f98167c1630fe2d745824cce8" FOREIGN KEY ("traineeId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trainee_progress" ADD CONSTRAINT "FK_02ded207ca1dd40e85d29feefd1" FOREIGN KEY ("coachId") REFERENCES "coach_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_2db9cf2b3ca111742793f6c37ce" FOREIGN KEY ("senderId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_acf951a58e3b9611dd96ce89042" FOREIGN KEY ("receiverId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "packages" ADD CONSTRAINT "FK_71b7c5e54bef5fa95df565979a3" FOREIGN KEY ("coachId") REFERENCES "coach_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "client_profiles" ADD CONSTRAINT "FK_af81cdb71317b2f0f6cb6bce776" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "client_profiles" DROP CONSTRAINT "FK_af81cdb71317b2f0f6cb6bce776"`);
        await queryRunner.query(`ALTER TABLE "packages" DROP CONSTRAINT "FK_71b7c5e54bef5fa95df565979a3"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_acf951a58e3b9611dd96ce89042"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_2db9cf2b3ca111742793f6c37ce"`);
        await queryRunner.query(`ALTER TABLE "trainee_progress" DROP CONSTRAINT "FK_02ded207ca1dd40e85d29feefd1"`);
        await queryRunner.query(`ALTER TABLE "trainee_progress" DROP CONSTRAINT "FK_34f98167c1630fe2d745824cce8"`);
        await queryRunner.query(`ALTER TABLE "coach_profiles" DROP CONSTRAINT "FK_e6994e1be0dd7a878d437bbbcc0"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`DROP TABLE "client_profiles"`);
        await queryRunner.query(`DROP TABLE "packages"`);
        await queryRunner.query(`DROP TYPE "public"."packages_skilllevel_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ce6acdb0801254590f8a78c08"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_15f9bd2bf472ff12b6ee20012d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_57eec5dc5b3e70ace7769466f8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_befd307485dbf0559d17e4a4d2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_acf951a58e3b9611dd96ce8904"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2db9cf2b3ca111742793f6c37c"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP TYPE "public"."messages_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."messages_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3bfcdfdee741415b1f37b3b6bf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8375e4aeb4b966f81293171fad"`);
        await queryRunner.query(`DROP TABLE "quotes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_481bbe1139541276b3dd613e22"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df1eb656efc9f5fda4f34565b3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_02ded207ca1dd40e85d29feefd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_34f98167c1630fe2d745824cce"`);
        await queryRunner.query(`DROP TABLE "trainee_progress"`);
        await queryRunner.query(`DROP TYPE "public"."trainee_progress_lastactivitytype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."trainee_progress_subscriptionstatus_enum"`);
        await queryRunner.query(`DROP TABLE "coach_profiles"`);
        await queryRunner.query(`DROP TYPE "public"."coach_profiles_fitnessareas_enum"`);
        await queryRunner.query(`DROP TYPE "public"."coach_profiles_gender_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f371d2426c88d4cafeec9b4f0f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7d1f61c30f0601093f80c5b053"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d84c274214f1881d1b9469841a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f610bb716b9281f07dd9c11d9f"`);
        await queryRunner.query(`DROP TABLE "workouts"`);
        await queryRunner.query(`DROP TYPE "public"."workouts_difficulty_enum"`);
        await queryRunner.query(`DROP TYPE "public"."workouts_workouttype_enum"`);
        await queryRunner.query(`DROP TABLE "meals"`);
        await queryRunner.query(`DROP TYPE "public"."meals_mealtype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5f0cceaef187f5c7884891c9e0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_692a909ee0fa9383e7859f9b40"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_92f5d3a7779be163cbea7916c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aef1c7aef3725068e5540f8f00"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "features"`);
        await queryRunner.query(`DROP TABLE "discount_options"`);
        await queryRunner.query(`DROP TABLE "target_audiences"`);
    }

}
